import os
import base64

try:
    import vertexai.preview
    from vertexai.preview.generative_models import GenerativeModel, Content, Part
except ImportError as e:  # Catch the specific ImportError
    msg.fail(f"Could not import necessary Vertex AI libraries: {e}")
    raise  # Re-raise the error so it's not ignored

from wasabi import msg

from dotenv import load_dotenv

from goldenverba.components.interfaces import Generator

load_dotenv()


class GeminiGenerator_Multimodal(Generator):
    """
    Gemini Generator.
    """

    def __init__(self):
        super().__init__()
        self.name = "Gemini"
        self.description = "Generator using Google's Gemini 1.5 Pro model"
        self.requires_library = ["vertexai"]
        self.requires_env = [
            "GOOGLE_APPLICATION_CREDENTIALS",
            "GOOGLE_CLOUD_PROJECT",
        ]
        self.streamable = True
        self.model_name = os.getenv("GEMINI_MODEL", "gemini-1.5-flash-002")
        self.context_window = 100000

    async def generate_pdf(
        self,
        prompt: str,
        context: str,
        pdf_data: bytes,
        model_name: str = None,
    ):
        """Generate a stream of response dicts based on a list of queries and list of contexts, and includes conversational context
        @parameter: queries : list[str] - List of queries
        @parameter: context : list[str] - List of contexts
        @parameter: conversation : dict - Conversational context
        @parameter: model_name : str - Optional model name to override the default one
        @returns Iterator[dict] - Token response generated by the Generator in this format {system:TOKEN, finish_reason:stop or empty}.
        """

        url = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
        if url == "":
            yield {
                "message": "Missing GOOGLE_CLOUD_PROJECT",
                "finish_reason": "stop",
            }

        project_id = os.getenv("GOOGLE_CLOUD_PROJECT")

        REGION = "us-central1"
        credentials_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
        if credentials_path:  # Check if credentials path is set
            import google.auth
            credentials, project_id_from_creds = google.auth.load_credentials_from_file(credentials_path)# credentials json file
            vertexai.init(project=project_id, location=REGION, credentials=credentials)
        else:
            vertexai.init(project=project_id, location=REGION)

        # Use provided model_name if available, otherwise fall back to self.model_name
        model_name_to_use = model_name if model_name is not None else self.model_name

        try:

            
            generative_multimodal_model = GenerativeModel(
                model_name_to_use,
            )

            print("Gkiri: before api call")
            response = await generative_multimodal_model.generate_content_async(
                [{'mime_type': 'application/pdf', 'data': pdf_data}, prompt],
                stream=False
            )
            print("Gkiri: after api call")
            print(response.text)


        except Exception:
            raise


