import os

try:
    import vertexai.preview
    from vertexai.preview.generative_models import GenerativeModel, Content, Part
except ImportError as e:  # Catch the specific ImportError
    msg.fail(f"Could not import necessary Vertex AI libraries: {e}")
    raise  # Re-raise the error so it's not ignored

from wasabi import msg

from dotenv import load_dotenv

from goldenverba.components.interfaces import Generator

load_dotenv()


class GeminiGenerator(Generator):
    """
    Gemini Generator.
    """

    def __init__(self):
        super().__init__()
        self.name = "Gemini"
        self.description = "Generator using Google's Gemini 1.5 Pro model"
        self.requires_library = ["vertexai"]
        self.requires_env = [
            "GOOGLE_APPLICATION_CREDENTIALS",
            "GOOGLE_CLOUD_PROJECT",
        ]
        self.streamable = True
        self.model_name = os.getenv("GEMINI_MODEL", "gemini-1.5-flash-002")
        self.context_window = 100000

    async def generate_stream(
        self,
        queries: list[str],
        context: list[str],
        conversation: dict = None,
        model_name: str = None,
    ):
        """Generate a stream of response dicts based on a list of queries and list of contexts, and includes conversational context
        @parameter: queries : list[str] - List of queries
        @parameter: context : list[str] - List of contexts
        @parameter: conversation : dict - Conversational context
        @parameter: model_name : str - Optional model name to override the default one
        @returns Iterator[dict] - Token response generated by the Generator in this format {system:TOKEN, finish_reason:stop or empty}.
        """

        url = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
        if url == "":
            yield {
                "message": "Missing GOOGLE_CLOUD_PROJECT",
                "finish_reason": "stop",
            }

        if conversation is None:
            conversation = {}
        messages = self.prepare_messages(queries, context, conversation)

        try:
            project_id = os.getenv("GOOGLE_CLOUD_PROJECT")

            REGION = "us-central1"
            credentials_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
            if credentials_path:  # Check if credentials path is set
                import google.auth
                credentials, project_id_from_creds = google.auth.load_credentials_from_file(credentials_path)# credentials json file
                vertexai.init(project=project_id, location=REGION, credentials=credentials)
            else:
                vertexai.init(project=project_id, location=REGION)

            # Use provided model_name if available, otherwise fall back to self.model_name
            model_name_to_use = model_name if model_name is not None else self.model_name
            
            generative_multimodal_model = GenerativeModel(
                model_name_to_use,
            )

            completion = await generative_multimodal_model.generate_content_async(
                stream=True, contents=messages
            )

            iter = completion.__aiter__()

            try:
                while True:
                    chunk = await iter.__anext__()
                    if len(chunk.candidates) > 0:
                        if len(chunk.candidates[0].content.parts) > 0:
                            yield {
                                "message": chunk.candidates[0].content.parts[0].text,
                                "finish_reason": chunk.candidates[0].finish_reason,
                            }
                        else:
                            yield {
                                "message": " < Canceled due SAFETY REASONS >",
                                "finish_reason": "",
                            }

            except StopAsyncIteration:
                yield {
                    "message": "",
                    "finish_reason": "stop",
                }
                pass

        except Exception:
            raise



    def prepare_messages(
        self, queries: list[str], context: list[str], conversation: dict[str, str]
    ):
        """
        Prepares a list of messages formatted for a Retrieval Augmented Generation chatbot system, including system instructions, previous conversation, and a new user query with context.

        @parameter queries: A list of strings representing the user queries to be answered.
        @parameter context: A list of strings representing the context information provided for the queries.
        @parameter conversation: A list of previous conversation messages that include the role and content.

        @returns A list of message dictionaries formatted for the chatbot. This includes an initial system message, the previous conversation messages, and the new user query encapsulated with the provided context.

        Each message in the list is a dictionary with 'role' and 'content' keys, where 'role' is either 'system' or 'user', and 'content' contains the relevant text. This will depend on the LLM used.
        """
        messages = []

        for message in conversation:
            messages.append(
                Content(role=message.type, parts=[Part.from_text(message.content)])
            )

        query = " ".join(queries)
        user_context = " ".join(context)

        messages.append(
            Content(
                role="user",
                parts=[
                    Part.from_text(
                        f"{user_context} Please answer this query: '{query}' with this provided context. Only use the context if it is necessary to answer the question."
                    )
                ],
            )
        )

        messages = self.ensure_user_model_alteration(messages)

        return messages

    def ensure_user_model_alteration(self, messages):
        current_role: str = ""

        new_messages: list[Content] = []

        for message in messages:
            if message.role == "system":
                message.role = "model"

        if messages[0].role == "model":
            messages = messages[1:]

        for message in messages:
            if message.role == current_role:
                new_messages[-1] = message
            else:
                new_messages.append(message)
                current_role = message.role

        return new_messages



    async def generate_pdf_nostream(
        self,
        prompt: str,
        pdf_data: bytes,
        model_name: str = None,
    ):
        """Generate a response for PDF content using Gemini API
        
        Args:
            prompt (str): The prompt to send to the model
            pdf_data (bytes): The PDF file data in base64 encoded format
            model_name (str, optional): Optional model name override
            
        Yields:
            dict: Response containing message and finish reason
        """
        url = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
        if url == "":
            yield {
                "message": "Missing GOOGLE_CLOUD_PROJECT",
                "finish_reason": "error",
            }
            return

        try:
            project_id = os.getenv("GOOGLE_CLOUD_PROJECT")
            REGION = "us-central1"
            
            credentials_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
            if credentials_path:
                import google.auth
                credentials, project_id_from_creds = google.auth.load_credentials_from_file(credentials_path)
                vertexai.init(project=project_id, location=REGION, credentials=credentials)
            else:
                vertexai.init(project=project_id, location=REGION)

            model_name_to_use = model_name if model_name is not None else self.model_name
            
            generative_multimodal_model = GenerativeModel(model_name_to_use)

            # Create Content object with PDF and prompt
            response = await generative_multimodal_model.generate_content_async(
                [
                    {'mime_type': 'application/pdf', 'data': pdf_data},
                    prompt
                ]
            )

            # Extract and yield the response text
            if response.candidates:
                yield {
                    "message": response.text,
                    "finish_reason": response.candidates[0].finish_reason
                }
            else:
                yield {
                    "message": "",
                    "finish_reason": "error"
                }

        except Exception as e:
            yield {
                "message": f"An error occurred: {str(e)}",
                "finish_reason": "error",
            }
