export type PageType = "CHAT" | "DOCUMENTS" | "STATUS" | "ADD" | "SETTINGS" | "RAG" | "PROFILE" | "MOCK_EXAM_START" | "MOCK_EXAM" | "ADD_MOCKS" | "AI_MENTOR";

export const PAGE_TYPES = {
  CHAT: "CHAT",
  DOCUMENTS: "DOCUMENTS",
  STATUS: "STATUS",
  ADD: "ADD",
  SETTINGS: "SETTINGS",
  RAG: "RAG",
  PROFILE: "PROFILE",
  MOCK_EXAM_START: "MOCK_EXAM_START",
  MOCK_EXAM: "MOCK_EXAM",
  ADD_MOCKS: "ADD_MOCKS",
  AI_MENTOR: "AI_MENTOR"
} as const;
